


const UserRecInfoComponent = [
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac lectus ut mauris feugiat lacinia non at libero. Ut vehicula justo ac nunc porttitor, auctor luctus orci varius. Sed non eros quis sapien viverra dapibus. Nullam ullamcorper purus eu libero tristique, eget sodales odio ultricies. In euismod justo nec congue ultricies. Proin et bibendum velit. Sed sed augue mauris. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac lectus ut mauris feugiat lacinia non at libero. Ut vehicula justo ac nunc porttitor, auctor luctus orci varius. Sed non eros quis sapien viverra dapibus. Nullam ullamcorper purus eu libero tristique, eget sodales odio ultricies. In euismod justo nec congue ultricies. Proin et bibendum velit. Sed sed augue mauris.",
  
  "Fusce auctor, libero non tempus lacinia, felis diam feugiat mi, id commodo mauris libero vel odio. Nullam tincidunt, leo id vestibulum convallis, ligula libero ultrices leo, vitae aliquam nisl metus vel enim. Sed mattis ipsum a libero aliquet, eu lobortis augue volutpat. Nam ac sollicitudin ex. Integer vel justo sit amet orci malesuada efficitur. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae. Fusce auctor, libero non tempus lacinia, felis diam feugiat mi, id commodo mauris libero vel odio. Nullam tincidunt, leo id vestibulum convallis, ligula libero ultrices leo, vitae aliquam nisl metus vel enim. Sed mattis ipsum a libero aliquet, eu lobortis augue volutpat. Nam ac sollicitudin ex. Integer vel justo sit amet orci malesuada efficitur. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae.",
  
  "Curabitur vitae tortor quis tellus dictum eleifend. Vivamus id metus quis velit luctus finibus. Morbi ut tortor vel arcu sodales pulvinar. Duis nec efficitur elit, ac elementum quam. Fusce feugiat, felis at aliquet malesuada, sapien lacus blandit odio, non ultrices mi tortor nec justo. Suspendisse fermentum dolor eu luctus egestas. Maecenas sit amet massa id ligula ullamcorper ultricies. Integer quis scelerisque velit. Curabitur vitae tortor quis tellus dictum eleifend. Vivamus id metus quis velit luctus finibus. Morbi ut tortor vel arcu sodales pulvinar. Duis nec efficitur elit, ac elementum quam. Fusce feugiat, felis at aliquet malesuada, sapien lacus blandit odio, non ultrices mi tortor nec justo. Suspendisse fermentum dolor eu luctus egestas. Maecenas sit amet massa id ligula ullamcorper ultricies. Integer quis scelerisque velit.",

  "Etiam quis augue nec felis congue varius. Nullam euismod finibus tortor, eu malesuada ipsum volutpat at. Vivamus ac tristique elit. Sed vel libero vel libero malesuada sollicitudin. In lacinia urna nec libero gravida, eu consectetur justo efficitur. Sed ut odio vel mi volutpat tristique. Praesent et tristique justo, id congue odio. Nullam laoreet ipsum ut mauris vulputate, a ullamcorper odio vehicula. Etiam quis augue nec felis congue varius. Nullam euismod finibus tortor, eu malesuada ipsum volutpat at. Vivamus ac tristique elit. Sed vel libero vel libero malesuada sollicitudin. In lacinia urna nec libero gravida, eu consectetur justo efficitur. Sed ut odio vel mi volutpat tristique. Praesent et tristique justo, id congue odio. Nullam laoreet ipsum ut mauris vulputate, a ullamcorper odio vehicula." ,

  "Phasellus in purus vel libero fringilla tincidunt. Sed pulvinar, risus eget malesuada facilisis, lacus nisi accumsan nulla, eu dignissim elit ligula non odio. Fusce ac lacinia augue. Integer vel fringilla ligula. Praesent efficitur metus ut leo suscipit, vel tempus quam imperdiet. Duis nec sapien nec tellus blandit tincidunt ac at metus. Fusce eu fringilla odio. Aliquam sit amet dolor at ligula cursus fringilla. Phasellus in purus vel libero fringilla tincidunt. Sed pulvinar, risus eget malesuada facilisis, lacus nisi accumsan nulla, eu dignissim elit ligula non odio. Fusce ac lacinia augue. Integer vel fringilla ligula. Praesent efficitur metus ut leo suscipit, vel tempus quam imperdiet. Duis nec sapien nec tellus blandit tincidunt ac at metus. Fusce eu fringilla odio. Aliquam sit amet dolor at ligula cursus fringilla."

  ];
  
  
export default UserRecInfoComponent;